ALTER TABLE public.settings
ADD COLUMN IF NOT EXISTS portfolio_badge text DEFAULT 'View Our Work',
ADD COLUMN IF NOT EXISTS portfolio_title text DEFAULT 'Recent Masterpieces',
ADD COLUMN IF NOT EXISTS portfolio_description text DEFAULT 'A glimpse into the visual identities we''ve crafted for brands around the globe.',
ADD COLUMN IF NOT EXISTS pricing_badge text DEFAULT 'Clear Pricing',
ADD COLUMN IF NOT EXISTS pricing_title text DEFAULT 'Simple, transparent pricing',
ADD COLUMN IF NOT EXISTS pricing_description text DEFAULT 'No hidden fees. No surprise charges. Choose the plan that best fits your brand needs.',
ADD COLUMN IF NOT EXISTS process_badge text DEFAULT 'Our Process',
ADD COLUMN IF NOT EXISTS process_title text DEFAULT '4 simple steps to launch',
ADD COLUMN IF NOT EXISTS process_description text DEFAULT 'We have eliminated the friction from traditional agency models.',
ADD COLUMN IF NOT EXISTS process_list jsonb DEFAULT '[
  {"title": "Penemuan", "desc": "Isi brief singkat tentang visi brand Anda.", "icon": "Search"},
  {"title": "Ideasi", "desc": "Desainer kami membuat konsep logo unik dalam 24-48 jam.", "icon": "Lightbulb"},
  {"title": "Penyempurnaan", "desc": "Kami bekerja sama untuk menyempurnakan desain Anda.", "icon": "Edit3"},
  {"title": "Pengiriman", "desc": "Terima semua file resolusi tinggi, vektor, dan file sumber.", "icon": "DownloadCloud"}
]'::jsonb,
ADD COLUMN IF NOT EXISTS case_studies_title text DEFAULT 'More Case Studies',
ADD COLUMN IF NOT EXISTS case_studies_description text DEFAULT 'A curated collection of our finest brand identity projects.',
ADD COLUMN IF NOT EXISTS faq_badge text DEFAULT 'Got Questions?',
ADD COLUMN IF NOT EXISTS faq_title text DEFAULT 'Frequently asked questions',
ADD COLUMN IF NOT EXISTS faq_description text DEFAULT 'If you can''t find what you''re looking for, feel free to contact our support team.',
ADD COLUMN IF NOT EXISTS cta_title text DEFAULT 'Ready to elevate your brand?',
ADD COLUMN IF NOT EXISTS cta_description text DEFAULT 'Join thousands of successful businesses who trust us with their visual identity.',
ADD COLUMN IF NOT EXISTS cta_button1_text text DEFAULT 'Let''s get started',
ADD COLUMN IF NOT EXISTS cta_button2_text text DEFAULT 'Talk to our team',
ADD COLUMN IF NOT EXISTS blog_badge text DEFAULT 'Our Blog',
ADD COLUMN IF NOT EXISTS blog_title text DEFAULT 'Latest insights',
ADD COLUMN IF NOT EXISTS blog_description text DEFAULT 'Expert advice, design principles, and strategies to help your brand stand out.',
ADD COLUMN IF NOT EXISTS hero_badge text DEFAULT 'Fast, Premium Logo Design',
ADD COLUMN IF NOT EXISTS hero_title text DEFAULT 'Design your brand''s perfect identity',
ADD COLUMN IF NOT EXISTS hero_description text DEFAULT 'Professional logo design that speaks to your audience.',
ADD COLUMN IF NOT EXISTS features_list jsonb DEFAULT '[
  {"title": "Lightning Fast", "desc": "Get your initial logo concepts in less than 24 hours.", "icon": "Rocket"},
  {"title": "Premium Quality", "desc": "Crafted by expert designers with years of branding experience.", "icon": "Sparkles"},
  {"title": "Unlimited Revisions", "desc": "We are not happy until you are. Tweak it until it''s perfect.", "icon": "CheckCircle2"}
]'::jsonb,
ADD COLUMN IF NOT EXISTS trusted_by_title text DEFAULT 'Trusted by 5,000+ ambitious brands',
ADD COLUMN IF NOT EXISTS trusted_by_description text DEFAULT 'From stealth startups to global enterprises, we deliver world-class visual identities.',
ADD COLUMN IF NOT EXISTS stats_title text DEFAULT 'Join the club',
ADD COLUMN IF NOT EXISTS stats_list jsonb DEFAULT '[
  {"value": "24", "suffix": "j", "label": "Rata-rata Pengiriman"},
  {"value": "∞", "suffix": "", "label": "Revisi Gratis"},
  {"value": "200", "suffix": "+", "label": "Ulasan Bintang 5"},
  {"value": "99", "suffix": "%", "label": "Kepuasan Klien"}
]'::jsonb,
ADD COLUMN IF NOT EXISTS testimonial_badge text DEFAULT 'Testimonials',
ADD COLUMN IF NOT EXISTS testimonial_title text DEFAULT 'What our clients say',
ADD COLUMN IF NOT EXISTS testimonial_description text DEFAULT 'Real words from real clients about their experience working with us.',
ADD COLUMN IF NOT EXISTS why_choose_us_badge text DEFAULT 'Kenapa Kami',
ADD COLUMN IF NOT EXISTS why_choose_us_title text DEFAULT 'Mengapa Memilih Kami?',
ADD COLUMN IF NOT EXISTS why_choose_us_description text DEFAULT 'Kami bukan sekadar jasa desain logo biasa. Kami adalah mitra pertumbuhan brand Anda.',
ADD COLUMN IF NOT EXISTS why_choose_us_list jsonb DEFAULT '[
  {"title": "Cepat & Tepat Waktu", "desc": "Konsep awal logo siap dalam 24 jam.", "icon": "Zap"},
  {"title": "Kualitas Premium", "desc": "Desainer berpengalaman dengan standar internasional.", "icon": "Sparkles"},
  {"title": "Revisi Tanpa Batas", "desc": "Kami tidak puas sampai Anda puas.", "icon": "RefreshCcw"},
  {"title": "Terpercaya", "desc": "Ratusan klien puas dari seluruh Indonesia.", "icon": "Shield"},
  {"title": "Harga Transparan", "desc": "Tidak ada biaya tersembunyi.", "icon": "CheckCircle2"},
  {"title": "Dukungan Penuh", "desc": "Tim kami siap membantu Anda kapan saja.", "icon": "Lightbulb"}
]'::jsonb,
ADD COLUMN IF NOT EXISTS all_services_badge text DEFAULT 'Layanan Kami',
ADD COLUMN IF NOT EXISTS all_services_title text DEFAULT 'Semua Layanan',
ADD COLUMN IF NOT EXISTS all_services_description text DEFAULT 'Temukan paket desain yang paling sesuai dengan kebutuhan bisnis Anda.';
